import React from 'react'
import { createRoot } from 'react-dom/client'
import {
  RouterProvider,
  createRouter,
  createRootRoute,
  createRoute,
  Outlet,
  redirect,
  Navigate,
  useLocation,
  useParams,
  Link,
} from '@tanstack/react-router'
import { MDXProvider } from '@mdx-js/react'
import { pages, sidebar } from 'virtual:prev-pages'
import { pageModules } from 'virtual:prev-page-modules'
import { previews } from 'virtual:prev-previews'
import { Preview } from './Preview'
import { useDiagrams } from './diagrams'
import { Layout } from './Layout'
import { MetadataBlock } from './MetadataBlock'
import { mdxComponents } from './mdx-components'
import { DevToolsProvider } from './DevToolsContext'
import './styles.css'

// PageTree types (simplified from fumadocs-core)
namespace PageTree {
  export interface Item {
    type: 'page'
    name: string
    url: string
  }
  export interface Folder {
    type: 'folder'
    name: string
    children: (Item | Folder)[]
  }
  export interface Root {
    name: string
    children: (Item | Folder)[]
  }
}

// Convert prev-cli sidebar to Fumadocs PageTree format
function convertToPageTree(items: any[]): PageTree.Root {
  function convertItem(item: any): PageTree.Item | PageTree.Folder {
    if (item.children) {
      return {
        type: 'folder',
        name: item.title,
        children: item.children.map(convertItem),
      }
    }
    return {
      type: 'page',
      name: item.title,
      url: item.route || '/',
    }
  }

  return {
    name: 'docs',
    children: items.map(convertItem),
  }
}

// Page modules are dynamically generated by the pages plugin
// This ensures all MDX files are included regardless of dot-prefixed directories
function getPageComponent(file: string): React.ComponentType | null {
  const mod = pageModules[`/${file}`]
  return mod?.default || null
}

interface PageMeta {
  title?: string
  description?: string
  frontmatter?: Record<string, unknown>
}

// Page wrapper that renders diagrams after content loads
function PageWrapper({ Component, meta }: { Component: React.ComponentType; meta: PageMeta }) {
  useDiagrams()
  return (
    <MDXProvider components={mdxComponents}>
      {meta.frontmatter && Object.keys(meta.frontmatter).length > 0 && (
        <MetadataBlock frontmatter={meta.frontmatter} />
      )}
      <Component />
    </MDXProvider>
  )
}

// Previews catalog - Storybook-like gallery with clickable cards
function PreviewsCatalog() {
  if (!previews || previews.length === 0) {
    return (
      <div style={{ padding: '40px 20px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '16px' }}>
          No Previews Found
        </h1>
        <p style={{ color: 'var(--fd-muted-foreground)', marginBottom: '24px' }}>
          Create your first preview with:
        </p>
        <code style={{
          display: 'inline-block',
          padding: '12px 20px',
          backgroundColor: 'var(--fd-muted)',
          borderRadius: '8px',
          fontFamily: 'var(--fd-font-mono)',
        }}>
          prev create my-demo
        </code>
      </div>
    )
  }

  return (
    <div className="previews-catalog">
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '28px', fontWeight: 'bold', marginBottom: '8px' }}>
          Previews
        </h1>
        <p style={{ color: 'var(--fd-muted-foreground)', margin: 0 }}>
          {previews.length} component preview{previews.length !== 1 ? 's' : ''} available.
          Click any preview to open it.
        </p>
      </div>

      <div className="previews-grid">
        {previews.map((preview: { name: string; route: string }) => (
          <PreviewCard key={preview.name} name={preview.name} />
        ))}
      </div>

      <div style={{
        marginTop: '32px',
        padding: '14px 16px',
        backgroundColor: 'var(--fd-muted)',
        border: '1px solid var(--fd-border)',
        borderRadius: '10px',
      }}>
        <p style={{ margin: 0, fontSize: '14px', color: 'var(--fd-muted-foreground)' }}>
          <strong style={{ color: 'var(--fd-foreground)' }}>Tip:</strong> Embed any preview in your MDX docs with{' '}
          <code style={{ backgroundColor: 'var(--fd-accent)', padding: '2px 6px', borderRadius: '4px', fontFamily: 'var(--fd-font-mono)' }}>
            {'<Preview src="name" />'}
          </code>
        </p>
      </div>
    </div>
  )
}

// Individual preview card - clickable thumbnail with WASM preview communication
import type { PreviewConfig, PreviewMessage } from '../preview-runtime/types'

function PreviewCard({ name }: { name: string }) {
  const iframeRef = React.useRef<HTMLIFrameElement>(null)
  const [isLoaded, setIsLoaded] = React.useState(false)
  const [loadError, setLoadError] = React.useState(false)

  // In production, use pre-built static files; in dev, use WASM runtime
  const isDev = import.meta.env?.DEV ?? false
  const baseUrl = (import.meta.env?.BASE_URL ?? '/').replace(/\/$/, '')
  const previewUrl = isDev ? `/_preview-runtime?src=${name}` : `${baseUrl}/_preview/${name}/`

  // Timeout for loading - show placeholder if too slow
  React.useEffect(() => {
    const timeout = setTimeout(() => {
      if (!isLoaded) {
        setLoadError(true)
      }
    }, 5000) // 5 second timeout

    return () => clearTimeout(timeout)
  }, [isLoaded])

  // Set up WASM preview communication for thumbnail (dev mode only)
  React.useEffect(() => {
    if (!isDev) {
      // In production, just mark as loaded when iframe loads
      const iframe = iframeRef.current
      if (iframe) {
        iframe.onload = () => setIsLoaded(true)
        iframe.onerror = () => setLoadError(true)
      }
      return
    }

    const iframe = iframeRef.current
    if (!iframe) return

    let configSent = false

    const handleMessage = (event: MessageEvent) => {
      const msg = event.data as PreviewMessage

      if (msg.type === 'ready' && !configSent) {
        configSent = true

        fetch(`/_preview-config/${name}`)
          .then(res => res.json())
          .then((config: PreviewConfig) => {
            iframe.contentWindow?.postMessage({ type: 'init', config } as PreviewMessage, '*')
          })
          .catch(() => {
            setLoadError(true)
          })
      }

      if (msg.type === 'built') {
        setIsLoaded(true)
      }

      if (msg.type === 'error') {
        setLoadError(true)
      }
    }

    window.addEventListener('message', handleMessage)

    return () => {
      window.removeEventListener('message', handleMessage)
    }
  }, [name, isDev])

  return (
    <Link to={`/previews/${name}`} className="preview-card">
      {/* Thumbnail preview */}
      <div className="preview-card-thumbnail">
        {/* Loading state */}
        {!isLoaded && !loadError && (
          <div className="preview-card-loading">
            <div className="preview-card-spinner" />
          </div>
        )}
        {/* Error/timeout placeholder */}
        {loadError && (
          <div className="preview-card-placeholder">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <rect x="3" y="3" width="18" height="18" rx="2" />
              <path d="M9 9l6 6m0-6l-6 6" />
            </svg>
            <span>Preview</span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src={previewUrl}
          className="preview-card-iframe"
          style={{ opacity: isLoaded && !loadError ? 1 : 0 }}
          title={name}
          loading="lazy"
        />
      </div>
      {/* Card footer */}
      <div className="preview-card-footer">
        <h3 className="preview-card-title">{name}</h3>
        <code className="preview-card-path">previews/{name}/</code>
      </div>
    </Link>
  )
}

// Individual preview page - full view with devtools in toolbar
function PreviewPage() {
  const params = useParams({ strict: false })
  // Splat param captures the full path after /previews/
  const name = (params as any)['_splat'] || (params as any)['*'] || params.name as string

  if (!name) {
    return <Navigate to="/previews" />
  }

  return (
    <div className="preview-detail-page">
      <Preview src={name} height="100%" showHeader />
    </div>
  )
}

// Root layout with custom lightweight Layout
function RootLayout() {
  const pageTree = convertToPageTree(sidebar)
  const location = useLocation()
  const isPreviewDetail = location.pathname.startsWith('/previews/') && location.pathname !== '/previews'

  // Preview detail page gets full viewport layout
  if (isPreviewDetail) {
    return (
      <Layout tree={pageTree}>
        <Outlet />
      </Layout>
    )
  }

  return (
    <Layout tree={pageTree}>
      <article className="prev-content">
        <Outlet />
      </article>
    </Layout>
  )
}

// Create root route
const rootRoute = createRootRoute({
  component: RootLayout,
})

// Previews layout route (just passes through to children)
const previewsLayoutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/previews',
  component: () => <Outlet />,
})

// Previews catalog route (index)
const previewsCatalogRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '/',
  component: PreviewsCatalog,
})

// Individual preview route (splat captures nested paths like buttons/primary)
const previewDetailRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '$',
  component: PreviewPage,
})

// Check if we have an index page (route '/')
const hasIndexPage = pages.some((page: { route: string }) => page.route === '/')
const firstPage = pages[0] as { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> } | undefined

// Create routes from pages
const pageRoutes = pages.map((page: { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> }) => {
  const Component = getPageComponent(page.file)
  const meta: PageMeta = {
    title: page.title,
    description: page.description,
    frontmatter: page.frontmatter,
  }
  return createRoute({
    getParentRoute: () => rootRoute,
    path: page.route === '/' ? '/' : page.route,
    component: Component ? () => <PageWrapper Component={Component} meta={meta} /> : () => null,
  })
})

// If no index page exists, create a redirect from '/' to the first page
const indexRedirectRoute = !hasIndexPage && firstPage ? createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <Navigate to={firstPage.route} />,
}) : null

// Not found component - redirect to first page or index
function NotFoundPage() {
  const targetRoute = firstPage?.route || '/'
  return <Navigate to={targetRoute} />
}

// Create router with notFoundRoute
// Previews routes: layout with catalog (index) and detail (splat) children
const previewsRouteWithChildren = previewsLayoutRoute.addChildren([
  previewsCatalogRoute,
  previewDetailRoute,
])

const routeTree = rootRoute.addChildren([
  previewsRouteWithChildren,
  ...(indexRedirectRoute ? [indexRedirectRoute] : []),
  ...pageRoutes,
])
// Get base path for subpath deployments (e.g., GitHub Pages)
const basepath = (import.meta.env?.BASE_URL ?? '/').replace(/\/$/, '') || '/'

const router = createRouter({
  routeTree,
  basepath,
  defaultNotFoundComponent: NotFoundPage,
})

// Mount app - RouterProvider must be outermost so TanStack Router context is available
const container = document.getElementById('root')
if (container) {
  const root = createRoot(container)
  root.render(
    <DevToolsProvider>
      <RouterProvider router={router} />
    </DevToolsProvider>
  )
}
