import React from 'react'
import { createRoot } from 'react-dom/client'
import {
  RouterProvider,
  createRouter,
  createRootRoute,
  createRoute,
  Outlet,
  redirect,
  Navigate,
  useLocation,
  useParams,
  Link,
} from '@tanstack/react-router'
import { MDXProvider } from '@mdx-js/react'
import { pages, sidebar } from 'virtual:prev-pages'
import { pageModules } from 'virtual:prev-page-modules'
import { previewUnits } from 'virtual:prev-previews'
import type { PreviewUnit, PreviewType } from '../content/preview-types'
import { Preview } from './Preview'
import { TokensPage } from './previews/TokensPage'
import { useDiagrams } from './diagrams'
import { Layout } from './Layout'
import { MetadataBlock } from './MetadataBlock'
import { mdxComponents } from './mdx-components'
import { DevToolsProvider } from './DevToolsContext'
import './styles.css'

// PageTree types (simplified from fumadocs-core)
namespace PageTree {
  export interface Item {
    type: 'page'
    name: string
    url: string
  }
  export interface Folder {
    type: 'folder'
    name: string
    children: (Item | Folder)[]
  }
  export interface Root {
    name: string
    children: (Item | Folder)[]
  }
}

// Convert prev-cli sidebar to Fumadocs PageTree format
function convertToPageTree(items: any[]): PageTree.Root {
  function convertItem(item: any): PageTree.Item | PageTree.Folder {
    if (item.children) {
      return {
        type: 'folder',
        name: item.title,
        children: item.children.map(convertItem),
      }
    }
    return {
      type: 'page',
      name: item.title,
      url: item.route || '/',
    }
  }

  return {
    name: 'docs',
    children: items.map(convertItem),
  }
}

// Page modules are dynamically generated by the pages plugin
// This ensures all MDX files are included regardless of dot-prefixed directories
function getPageComponent(file: string): React.ComponentType | null {
  const mod = pageModules[`/${file}`]
  return mod?.default || null
}

interface PageMeta {
  title?: string
  description?: string
  frontmatter?: Record<string, unknown>
}

// Page wrapper that renders diagrams after content loads
function PageWrapper({ Component, meta }: { Component: React.ComponentType; meta: PageMeta }) {
  useDiagrams()
  return (
    <MDXProvider components={mdxComponents}>
      {meta.frontmatter && Object.keys(meta.frontmatter).length > 0 && (
        <MetadataBlock frontmatter={meta.frontmatter} />
      )}
      <Component />
    </MDXProvider>
  )
}

// Category metadata for display
const CATEGORY_META: Record<PreviewType, { label: string; icon: string; description: string }> = {
  component: {
    label: 'Components',
    icon: '⬡',
    description: 'Reusable UI building blocks',
  },
  screen: {
    label: 'Screens',
    icon: '▣',
    description: 'Full page layouts and views',
  },
  flow: {
    label: 'Flows',
    icon: '⇢',
    description: 'Multi-step user journeys',
  },
}

// Category display order
const CATEGORY_ORDER: PreviewType[] = ['component', 'screen', 'flow']

// Group previews by type
function groupByType(units: PreviewUnit[]): Map<PreviewType, PreviewUnit[]> {
  const grouped = new Map<PreviewType, PreviewUnit[]>()
  for (const unit of units) {
    const existing = grouped.get(unit.type) || []
    grouped.set(unit.type, [...existing, unit])
  }
  return grouped
}

// Category section component with carousel navigation
function CategorySection({ type, units }: { type: PreviewType; units: PreviewUnit[] }) {
  const meta = CATEGORY_META[type]
  const scrollRef = React.useRef<HTMLDivElement>(null)

  const scroll = (direction: 'left' | 'right') => {
    const container = scrollRef.current
    if (!container) return
    const cardWidth = 280 + 16 // card width + gap
    const scrollAmount = direction === 'left' ? -cardWidth : cardWidth
    container.scrollBy({ left: scrollAmount, behavior: 'smooth' })
  }

  return (
    <section className="category-section">
      <div className="category-header">
        <span className="category-icon">{meta.icon}</span>
        <div className="category-info">
          <h2 className="category-title">
            {meta.label}
            <span className="category-count">({units.length})</span>
          </h2>
          <p className="category-description">{meta.description}</p>
        </div>
        <div className="category-nav">
          <button
            type="button"
            className="category-nav-btn"
            onClick={() => scroll('left')}
            aria-label="Previous"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M15 18l-6-6 6-6" />
            </svg>
          </button>
          <button
            type="button"
            className="category-nav-btn"
            onClick={() => scroll('right')}
            aria-label="Next"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </button>
        </div>
      </div>
      <div className="previews-grid" ref={scrollRef}>
        {units.map((unit) => {
          const fullName = unit.route.replace(/^\/_preview\//, '')
          return (
            <PreviewCard
              key={fullName}
              name={fullName}
              title={unit.config?.title}
              status={unit.config?.status}
              type={unit.type}
            />
          )
        })}
      </div>
    </section>
  )
}

// Previews catalog - Storybook-like gallery with categorized sections
function PreviewsCatalog() {
  const units = previewUnits || []

  if (units.length === 0) {
    return (
      <div style={{ padding: '40px 20px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '16px' }}>
          No Previews Found
        </h1>
        <p style={{ color: 'var(--fd-muted-foreground)', marginBottom: '24px' }}>
          Create your first preview with:
        </p>
        <code style={{
          display: 'inline-block',
          padding: '12px 20px',
          backgroundColor: 'var(--fd-muted)',
          borderRadius: '8px',
          fontFamily: 'var(--fd-font-mono)',
        }}>
          prev create my-demo
        </code>
      </div>
    )
  }

  const grouped = groupByType(units)
  const totalCount = units.length

  return (
    <div className="previews-catalog">
      {/* Header */}
      <div className="catalog-header">
        <h1 className="catalog-title">Previews</h1>
        <p className="catalog-subtitle">
          {totalCount} preview{totalCount !== 1 ? 's' : ''} across {grouped.size} categor{grouped.size !== 1 ? 'ies' : 'y'}
        </p>
      </div>

      {/* Categorized sections */}
      {CATEGORY_ORDER.map((type) => {
        const units = grouped.get(type)
        if (!units || units.length === 0) return null
        return <CategorySection key={type} type={type} units={units} />
      })}

      {/* Tip - hidden on mobile */}
      <div className="catalog-tip">
        <p>
          <strong>Tip:</strong> Embed any preview in your MDX docs with{' '}
          <code>{'<Preview src="name" />'}</code>
        </p>
      </div>
    </div>
  )
}

// Individual preview card - clickable thumbnail with WASM preview communication
import type { PreviewConfig, PreviewMessage } from '../preview-runtime/types'

function PreviewCard({ name, title, status, type }: { name: string; title?: string; status?: 'draft' | 'stable' | 'deprecated'; type?: PreviewType }) {
  // Config-only types (flow) have no JS entry point — show a styled placeholder instead of iframe
  const isConfigOnly = type === 'flow'

  const iframeRef = React.useRef<HTMLIFrameElement>(null)
  // In production, start as loaded since static files are fast
  const isDev = import.meta.env.DEV ?? false
  const [isLoaded, setIsLoaded] = React.useState(!isDev || isConfigOnly)
  const [loadError, setLoadError] = React.useState(false)

  const baseUrl = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '')
  const previewUrl = isConfigOnly ? '' : (isDev ? `/_preview-runtime?src=${name}` : `${baseUrl}/_preview/${name}/`)

  // Timeout for loading - only needed in dev mode
  React.useEffect(() => {
    if (!isDev || isConfigOnly) return

    const timeout = setTimeout(() => {
      if (!isLoaded) {
        setLoadError(true)
      }
    }, 5000)

    return () => clearTimeout(timeout)
  }, [isLoaded, isDev, isConfigOnly])

  // Set up WASM preview communication for thumbnail (dev mode only)
  React.useEffect(() => {
    if (!isDev || isConfigOnly) return

    const iframe = iframeRef.current
    if (!iframe) return

    let configSent = false

    const handleMessage = (event: MessageEvent) => {
      const msg = event.data as PreviewMessage

      if (msg.type === 'ready' && !configSent) {
        configSent = true

        fetch(`/_preview-config/${name}`)
          .then(res => res.json())
          .then((config: PreviewConfig) => {
            iframe.contentWindow?.postMessage({ type: 'init', config } as PreviewMessage, '*')
          })
          .catch(() => {
            setLoadError(true)
          })
      }

      if (msg.type === 'built') {
        setIsLoaded(true)
      }

      if (msg.type === 'error') {
        setLoadError(true)
      }
    }

    window.addEventListener('message', handleMessage)

    return () => {
      window.removeEventListener('message', handleMessage)
    }
  }, [name, isDev])

  return (
    <Link to={`/previews/${name}`} className="preview-card">
      {/* Thumbnail preview */}
      <div className="preview-card-thumbnail">
        {isConfigOnly ? (
          /* Config-only types: styled placeholder with category icon */
          <div className="preview-card-placeholder" style={{ opacity: 1 }}>
            <span style={{ fontSize: '32px' }}>⇢</span>
            <span>Flow</span>
          </div>
        ) : (
          <>
            {/* Loading state */}
            {!isLoaded && !loadError && (
              <div className="preview-card-loading">
                <div className="preview-card-spinner" />
              </div>
            )}
            {/* Error/timeout placeholder */}
            {loadError && (
              <div className="preview-card-placeholder">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <rect x="3" y="3" width="18" height="18" rx="2" />
                  <path d="M9 9l6 6m0-6l-6 6" />
                </svg>
                <span>Preview</span>
              </div>
            )}
            <iframe
              ref={iframeRef}
              src={previewUrl}
              className="preview-card-iframe"
              style={{ opacity: isLoaded && !loadError ? 1 : 0 }}
              title={name}
              loading="lazy"
            />
          </>
        )}
      </div>
      {/* Card footer */}
      <div className="preview-card-footer">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <h3 className="preview-card-title">{title || name}</h3>
          {status && status !== 'stable' && (
            <span style={{
              fontSize: '10px',
              fontWeight: '500',
              padding: '2px 6px',
              borderRadius: '4px',
              backgroundColor: status === 'draft' ? 'var(--fd-warning-background, #fef3c7)' : 'var(--fd-muted)',
              color: status === 'draft' ? 'var(--fd-warning-foreground, #92400e)' : 'var(--fd-muted-foreground)',
              textTransform: 'uppercase',
            }}>
              {status}
            </span>
          )}
        </div>
        <code className="preview-card-path">previews/{name}/</code>
      </div>
    </Link>
  )
}

// Individual preview page - full view with devtools in toolbar
// Uses specialized component for flow, generic Preview for components/screens
import { FlowPreview } from './previews/FlowPreview'

// Standalone preview embed (for iframe thumbnails in production)
// Renders just the preview content without Layout wrapper
function PreviewEmbed() {
  const params = useParams({ strict: false })
  const name = (params as any)['_splat'] || (params as any)['*'] || ''

  // In production, always use pre-built static files
  const isDev = import.meta.env.DEV ?? false
  const baseUrl = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '')

  // Parse type from name (e.g., "flows/checkout" -> type="flow", unitName="checkout")
  const match = name.match(/^(components|screens|flows)\/(.+)$/)
  if (!match) {
    // Fallback for legacy preview paths without type prefix
    const previewUrl = isDev ? `/_preview-runtime?src=${name}` : `${baseUrl}/_preview/${name}/`
    return (
      <iframe
        src={previewUrl}
        style={{ width: '100%', height: '100vh', border: 'none' }}
        title={name}
      />
    )
  }

  const [, typeFolder, unitName] = match
  const type = typeFolder === 'flows' ? 'flow' : typeFolder.slice(0, -1)

  // Find the preview unit
  const unit = previewUnits.find(u => u.type === type && u.name === unitName)

  if (!unit) {
    return (
      <div style={{ padding: '32px', textAlign: 'center', color: '#888' }}>
        Preview not found: {name}
      </div>
    )
  }

  // For flows, render the specialized component
  if (unit.type === 'flow') {
    return <FlowPreview unit={unit} />
  }

  // For components and screens, use iframe to load static HTML
  const previewUrl = isDev ? `/_preview-runtime?src=${name}` : `${baseUrl}/_preview/${name}/`
  return (
    <iframe
      src={previewUrl}
      style={{ width: '100%', height: '100vh', border: 'none' }}
      title={name}
    />
  )
}

function PreviewPage() {
  const params = useParams({ strict: false })
  // Splat param captures the full path after /previews/
  const name = (params as any)['_splat'] || (params as any)['*'] || params.name as string
  const [selectedState, setSelectedState] = React.useState<string | null>(null)

  if (!name) {
    return <Navigate to="/previews" />
  }

  // Find the preview unit to determine the type
  const unit = previewUnits.find(u => {
    // Match by route suffix (e.g., "flows/onboarding" matches route "/_preview/flows/onboarding")
    return u.route.endsWith(`/${name}`) || `${u.type}s/${u.name}` === name
  })

  // For flows, use the specialized component
  if (unit?.type === 'flow') {
    return (
      <div className="preview-detail-page">
        <FlowPreview unit={unit} />
      </div>
    )
  }

  // Get states for screens
  const states = unit?.files?.states || []
  const hasStates = states.length > 0

  // For components and screens, use the generic Preview with iframe
  return (
    <div className="preview-detail-page">
      {/* State selector for screens with multiple states */}
      {hasStates && (
        <div className="preview-state-selector">
          <span className="preview-state-label">State:</span>
          <div className="preview-state-buttons">
            <button
              type="button"
              className={`preview-state-btn ${selectedState === null ? 'active' : ''}`}
              onClick={() => setSelectedState(null)}
            >
              Default
            </button>
            {states.map((stateFile: string) => {
              const stateName = stateFile.replace(/\.(tsx|jsx)$/, '')
              const isSelected = selectedState === stateName
              return (
                <button
                  key={stateFile}
                  type="button"
                  className={`preview-state-btn ${isSelected ? 'active' : ''}`}
                  onClick={() => setSelectedState(stateName)}
                >
                  {stateName.replace(/[-_]/g, ' ')}
                </button>
              )
            })}
          </div>
        </div>
      )}
      <Preview src={name} state={selectedState} height="100%" showHeader />
    </div>
  )
}

// Root layout with custom lightweight Layout
function RootLayout() {
  const pageTree = convertToPageTree(sidebar)
  const location = useLocation()
  const isPreviewDetail = location.pathname.startsWith('/previews/') && location.pathname !== '/previews'

  // Preview detail page gets full viewport layout
  if (isPreviewDetail) {
    return (
      <Layout tree={pageTree}>
        <Outlet />
      </Layout>
    )
  }

  return (
    <Layout tree={pageTree}>
      <article className="prev-content">
        <Outlet />
      </article>
    </Layout>
  )
}

// Create root route
const rootRoute = createRootRoute({
  component: RootLayout,
})

// Previews layout route (just passes through to children)
const previewsLayoutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/previews',
  component: () => <Outlet />,
})

// Previews catalog route (index)
const previewsCatalogRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '/',
  component: PreviewsCatalog,
})

// Individual preview route (splat captures nested paths like buttons/primary)
const previewDetailRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '$',
  component: PreviewPage,
})

// Tokens showcase route (design system tokens reference)
const tokensRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/_prev/tokens',
  component: TokensPage,
})

// Standalone preview embed route (handles /_preview/flows/checkout, /_preview/atlas/app, etc.)
// This is used when thumbnails load as iframes - the 404.html serves the SPA which matches this route
const previewEmbedRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/_preview/$',
  component: PreviewEmbed,
})

// Check if we have an index page (route '/')
const hasIndexPage = pages.some((page: { route: string }) => page.route === '/')
const firstPage = pages[0] as { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> } | undefined

// Create routes from pages
const pageRoutes = pages.map((page: { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> }) => {
  const Component = getPageComponent(page.file)
  const meta: PageMeta = {
    title: page.title,
    description: page.description,
    frontmatter: page.frontmatter,
  }
  return createRoute({
    getParentRoute: () => rootRoute,
    path: page.route === '/' ? '/' : page.route,
    component: Component ? () => <PageWrapper Component={Component} meta={meta} /> : () => null,
  })
})

// If no index page exists, create a redirect from '/' to the first page
const indexRedirectRoute = !hasIndexPage && firstPage ? createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <Navigate to={firstPage.route} />,
}) : null

// Not found component - redirect to first page or index
function NotFoundPage() {
  const targetRoute = firstPage?.route || '/'
  return <Navigate to={targetRoute} />
}

// Create router with notFoundRoute
// Previews routes: layout with catalog (index) and detail (splat) children
const previewsRouteWithChildren = previewsLayoutRoute.addChildren([
  previewsCatalogRoute,
  previewDetailRoute,
])

const routeTree = rootRoute.addChildren([
  previewsRouteWithChildren,
  tokensRoute,
  previewEmbedRoute,
  ...(indexRedirectRoute ? [indexRedirectRoute] : []),
  ...pageRoutes,
])
// Get base path for subpath deployments (e.g., GitHub Pages)
const basepath = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '') || '/'

const router = createRouter({
  routeTree,
  basepath,
  defaultNotFoundComponent: NotFoundPage,
})

// Mount app - RouterProvider must be outermost so TanStack Router context is available
const container = document.getElementById('root')
if (container) {
  const root = createRoot(container)
  root.render(
    <DevToolsProvider>
      <RouterProvider router={router} />
    </DevToolsProvider>
  )
}
