import React from 'react'
import { createRoot } from 'react-dom/client'
import {
  RouterProvider,
  createRouter,
  createRootRoute,
  createRoute,
  Outlet,
  redirect,
  Navigate,
  useLocation,
  useParams,
  Link,
} from '@tanstack/react-router'
import { MDXProvider } from '@mdx-js/react'
import { pages, sidebar } from 'virtual:prev-pages'
import { pageModules } from 'virtual:prev-page-modules'
import { previews, previewUnits } from 'virtual:prev-previews'
import type { PreviewUnit, PreviewType } from '../vite/preview-types'
import { Preview } from './Preview'
import { TokensPage } from './previews/TokensPage'
import { useDiagrams } from './diagrams'
import { Layout } from './Layout'
import { MetadataBlock } from './MetadataBlock'
import { mdxComponents } from './mdx-components'
import { DevToolsProvider } from './DevToolsContext'
import './styles.css'

// PageTree types (simplified from fumadocs-core)
namespace PageTree {
  export interface Item {
    type: 'page'
    name: string
    url: string
  }
  export interface Folder {
    type: 'folder'
    name: string
    children: (Item | Folder)[]
  }
  export interface Root {
    name: string
    children: (Item | Folder)[]
  }
}

// Convert prev-cli sidebar to Fumadocs PageTree format
function convertToPageTree(items: any[]): PageTree.Root {
  function convertItem(item: any): PageTree.Item | PageTree.Folder {
    if (item.children) {
      return {
        type: 'folder',
        name: item.title,
        children: item.children.map(convertItem),
      }
    }
    return {
      type: 'page',
      name: item.title,
      url: item.route || '/',
    }
  }

  return {
    name: 'docs',
    children: items.map(convertItem),
  }
}

// Page modules are dynamically generated by the pages plugin
// This ensures all MDX files are included regardless of dot-prefixed directories
function getPageComponent(file: string): React.ComponentType | null {
  const mod = pageModules[`/${file}`]
  return mod?.default || null
}

interface PageMeta {
  title?: string
  description?: string
  frontmatter?: Record<string, unknown>
}

// Page wrapper that renders diagrams after content loads
function PageWrapper({ Component, meta }: { Component: React.ComponentType; meta: PageMeta }) {
  useDiagrams()
  return (
    <MDXProvider components={mdxComponents}>
      {meta.frontmatter && Object.keys(meta.frontmatter).length > 0 && (
        <MetadataBlock frontmatter={meta.frontmatter} />
      )}
      <Component />
    </MDXProvider>
  )
}

// Category metadata for display
const CATEGORY_META: Record<PreviewType, { label: string; icon: string; description: string }> = {
  component: {
    label: 'Components',
    icon: '⬡',
    description: 'Reusable UI building blocks',
  },
  screen: {
    label: 'Screens',
    icon: '▣',
    description: 'Full page layouts and views',
  },
  flow: {
    label: 'Flows',
    icon: '⇢',
    description: 'Multi-step user journeys',
  },
  atlas: {
    label: 'Atlas',
    icon: '◎',
    description: 'Information architecture maps',
  },
}

// Category display order
const CATEGORY_ORDER: PreviewType[] = ['component', 'screen', 'flow', 'atlas']

// Group previews by type
function groupByType(units: PreviewUnit[]): Map<PreviewType, PreviewUnit[]> {
  const grouped = new Map<PreviewType, PreviewUnit[]>()
  for (const unit of units) {
    const existing = grouped.get(unit.type) || []
    grouped.set(unit.type, [...existing, unit])
  }
  return grouped
}

// Category section component
function CategorySection({ type, units }: { type: PreviewType; units: PreviewUnit[] }) {
  const meta = CATEGORY_META[type]

  return (
    <section style={{ marginBottom: '32px' }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginBottom: '16px',
        paddingBottom: '12px',
        borderBottom: '1px solid var(--fd-border)',
      }}>
        <span style={{ fontSize: '20px' }}>{meta.icon}</span>
        <div>
          <h2 style={{
            fontSize: '18px',
            fontWeight: '600',
            margin: 0,
            color: 'var(--fd-foreground)',
          }}>
            {meta.label}
            <span style={{
              marginLeft: '8px',
              fontSize: '14px',
              fontWeight: '400',
              color: 'var(--fd-muted-foreground)',
            }}>
              ({units.length})
            </span>
          </h2>
          <p style={{
            fontSize: '13px',
            color: 'var(--fd-muted-foreground)',
            margin: 0,
          }}>
            {meta.description}
          </p>
        </div>
      </div>
      <div className="previews-grid">
        {units.map((unit) => {
          // Extract full path name from route (e.g., "/_preview/components/button" -> "components/button")
          const fullName = unit.route.replace(/^\/_preview\//, '')
          return (
            <PreviewCard
              key={fullName}
              name={fullName}
              title={unit.config?.title}
              status={unit.config?.status}
            />
          )
        })}
      </div>
    </section>
  )
}

// Previews catalog - Storybook-like gallery with categorized sections
function PreviewsCatalog() {
  // Use previewUnits for categorization, fall back to legacy previews
  const units = previewUnits || []
  const legacyPreviews = previews || []

  // If no units but have legacy previews, convert them
  const allUnits: PreviewUnit[] = units.length > 0 ? units : legacyPreviews.map((p: { name: string; route: string }) => ({
    type: 'component' as PreviewType,
    name: p.name,
    path: '',
    route: p.route,
    config: null,
    files: { index: '' },
  }))

  if (allUnits.length === 0) {
    return (
      <div style={{ padding: '40px 20px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '16px' }}>
          No Previews Found
        </h1>
        <p style={{ color: 'var(--fd-muted-foreground)', marginBottom: '24px' }}>
          Create your first preview with:
        </p>
        <code style={{
          display: 'inline-block',
          padding: '12px 20px',
          backgroundColor: 'var(--fd-muted)',
          borderRadius: '8px',
          fontFamily: 'var(--fd-font-mono)',
        }}>
          prev create my-demo
        </code>
      </div>
    )
  }

  const grouped = groupByType(allUnits)
  const totalCount = allUnits.length

  return (
    <div className="previews-catalog">
      {/* Header */}
      <div style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '28px', fontWeight: 'bold', marginBottom: '8px' }}>
          Previews
        </h1>
        <p style={{ color: 'var(--fd-muted-foreground)', margin: 0 }}>
          {totalCount} preview{totalCount !== 1 ? 's' : ''} across {grouped.size} categor{grouped.size !== 1 ? 'ies' : 'y'}.
          Click any preview to open it.
        </p>
      </div>

      {/* Categorized sections */}
      {CATEGORY_ORDER.map((type) => {
        const units = grouped.get(type)
        if (!units || units.length === 0) return null
        return <CategorySection key={type} type={type} units={units} />
      })}

      {/* Tip */}
      <div style={{
        marginTop: '32px',
        padding: '14px 16px',
        backgroundColor: 'var(--fd-muted)',
        border: '1px solid var(--fd-border)',
        borderRadius: '10px',
      }}>
        <p style={{ margin: 0, fontSize: '14px', color: 'var(--fd-muted-foreground)' }}>
          <strong style={{ color: 'var(--fd-foreground)' }}>Tip:</strong> Embed any preview in your MDX docs with{' '}
          <code style={{ backgroundColor: 'var(--fd-accent)', padding: '2px 6px', borderRadius: '4px', fontFamily: 'var(--fd-font-mono)' }}>
            {'<Preview src="name" />'}
          </code>
        </p>
      </div>
    </div>
  )
}

// Individual preview card - clickable thumbnail with WASM preview communication
import type { PreviewConfig, PreviewMessage } from '../preview-runtime/types'

function PreviewCard({ name, title, status }: { name: string; title?: string; status?: 'draft' | 'stable' | 'deprecated' }) {
  const iframeRef = React.useRef<HTMLIFrameElement>(null)
  const [isLoaded, setIsLoaded] = React.useState(false)
  const [loadError, setLoadError] = React.useState(false)

  // In production, use pre-built static files; in dev, use WASM runtime
  const isDev = import.meta.env?.DEV ?? false
  const baseUrl = (import.meta.env?.BASE_URL ?? '/').replace(/\/$/, '')
  const previewUrl = isDev ? `/_preview-runtime?src=${name}` : `${baseUrl}/_preview/${name}/`

  // Timeout for loading - show placeholder if too slow
  React.useEffect(() => {
    const timeout = setTimeout(() => {
      if (!isLoaded) {
        setLoadError(true)
      }
    }, 5000) // 5 second timeout

    return () => clearTimeout(timeout)
  }, [isLoaded])

  // Set up WASM preview communication for thumbnail (dev mode only)
  React.useEffect(() => {
    if (!isDev) {
      // In production, just mark as loaded when iframe loads
      const iframe = iframeRef.current
      if (iframe) {
        iframe.onload = () => setIsLoaded(true)
        iframe.onerror = () => setLoadError(true)
      }
      return
    }

    const iframe = iframeRef.current
    if (!iframe) return

    let configSent = false

    const handleMessage = (event: MessageEvent) => {
      const msg = event.data as PreviewMessage

      if (msg.type === 'ready' && !configSent) {
        configSent = true

        fetch(`/_preview-config/${name}`)
          .then(res => res.json())
          .then((config: PreviewConfig) => {
            iframe.contentWindow?.postMessage({ type: 'init', config } as PreviewMessage, '*')
          })
          .catch(() => {
            setLoadError(true)
          })
      }

      if (msg.type === 'built') {
        setIsLoaded(true)
      }

      if (msg.type === 'error') {
        setLoadError(true)
      }
    }

    window.addEventListener('message', handleMessage)

    return () => {
      window.removeEventListener('message', handleMessage)
    }
  }, [name, isDev])

  return (
    <Link to={`/previews/${name}`} className="preview-card">
      {/* Thumbnail preview */}
      <div className="preview-card-thumbnail">
        {/* Loading state */}
        {!isLoaded && !loadError && (
          <div className="preview-card-loading">
            <div className="preview-card-spinner" />
          </div>
        )}
        {/* Error/timeout placeholder */}
        {loadError && (
          <div className="preview-card-placeholder">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <rect x="3" y="3" width="18" height="18" rx="2" />
              <path d="M9 9l6 6m0-6l-6 6" />
            </svg>
            <span>Preview</span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src={previewUrl}
          className="preview-card-iframe"
          style={{ opacity: isLoaded && !loadError ? 1 : 0 }}
          title={name}
          loading="lazy"
        />
      </div>
      {/* Card footer */}
      <div className="preview-card-footer">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <h3 className="preview-card-title">{title || name}</h3>
          {status && status !== 'stable' && (
            <span style={{
              fontSize: '10px',
              fontWeight: '500',
              padding: '2px 6px',
              borderRadius: '4px',
              backgroundColor: status === 'draft' ? 'var(--fd-warning-background, #fef3c7)' : 'var(--fd-muted)',
              color: status === 'draft' ? 'var(--fd-warning-foreground, #92400e)' : 'var(--fd-muted-foreground)',
              textTransform: 'uppercase',
            }}>
              {status}
            </span>
          )}
        </div>
        <code className="preview-card-path">previews/{name}/</code>
      </div>
    </Link>
  )
}

// Individual preview page - full view with devtools in toolbar
// Uses specialized components for flow/atlas, generic Preview for components/screens
import { FlowPreview } from './previews/FlowPreview'
import { AtlasPreview } from './previews/AtlasPreview'

function PreviewPage() {
  const params = useParams({ strict: false })
  // Splat param captures the full path after /previews/
  const name = (params as any)['_splat'] || (params as any)['*'] || params.name as string

  if (!name) {
    return <Navigate to="/previews" />
  }

  // Find the preview unit to determine the type
  const unit = previewUnits.find(u => {
    // Match by route suffix (e.g., "flows/onboarding" matches route "/_preview/flows/onboarding")
    return u.route.endsWith(`/${name}`) || `${u.type}s/${u.name}` === name
  })

  // For flows and atlas, use their specialized components
  if (unit?.type === 'flow') {
    return (
      <div className="preview-detail-page">
        <FlowPreview unit={unit} />
      </div>
    )
  }

  if (unit?.type === 'atlas') {
    return (
      <div className="preview-detail-page">
        <AtlasPreview unit={unit} />
      </div>
    )
  }

  // For components and screens, use the generic Preview with iframe
  return (
    <div className="preview-detail-page">
      <Preview src={name} height="100%" showHeader />
    </div>
  )
}

// Root layout with custom lightweight Layout
function RootLayout() {
  const pageTree = convertToPageTree(sidebar)
  const location = useLocation()
  const isPreviewDetail = location.pathname.startsWith('/previews/') && location.pathname !== '/previews'

  // Preview detail page gets full viewport layout
  if (isPreviewDetail) {
    return (
      <Layout tree={pageTree}>
        <Outlet />
      </Layout>
    )
  }

  return (
    <Layout tree={pageTree}>
      <article className="prev-content">
        <Outlet />
      </article>
    </Layout>
  )
}

// Create root route
const rootRoute = createRootRoute({
  component: RootLayout,
})

// Previews layout route (just passes through to children)
const previewsLayoutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/previews',
  component: () => <Outlet />,
})

// Previews catalog route (index)
const previewsCatalogRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '/',
  component: PreviewsCatalog,
})

// Individual preview route (splat captures nested paths like buttons/primary)
const previewDetailRoute = createRoute({
  getParentRoute: () => previewsLayoutRoute,
  path: '$',
  component: PreviewPage,
})

// Tokens showcase route (design system tokens reference)
const tokensRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/_prev/tokens',
  component: TokensPage,
})

// Check if we have an index page (route '/')
const hasIndexPage = pages.some((page: { route: string }) => page.route === '/')
const firstPage = pages[0] as { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> } | undefined

// Create routes from pages
const pageRoutes = pages.map((page: { route: string; file: string; title?: string; description?: string; frontmatter?: Record<string, unknown> }) => {
  const Component = getPageComponent(page.file)
  const meta: PageMeta = {
    title: page.title,
    description: page.description,
    frontmatter: page.frontmatter,
  }
  return createRoute({
    getParentRoute: () => rootRoute,
    path: page.route === '/' ? '/' : page.route,
    component: Component ? () => <PageWrapper Component={Component} meta={meta} /> : () => null,
  })
})

// If no index page exists, create a redirect from '/' to the first page
const indexRedirectRoute = !hasIndexPage && firstPage ? createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <Navigate to={firstPage.route} />,
}) : null

// Not found component - redirect to first page or index
function NotFoundPage() {
  const targetRoute = firstPage?.route || '/'
  return <Navigate to={targetRoute} />
}

// Create router with notFoundRoute
// Previews routes: layout with catalog (index) and detail (splat) children
const previewsRouteWithChildren = previewsLayoutRoute.addChildren([
  previewsCatalogRoute,
  previewDetailRoute,
])

const routeTree = rootRoute.addChildren([
  previewsRouteWithChildren,
  tokensRoute,
  ...(indexRedirectRoute ? [indexRedirectRoute] : []),
  ...pageRoutes,
])
// Get base path for subpath deployments (e.g., GitHub Pages)
const basepath = (import.meta.env?.BASE_URL ?? '/').replace(/\/$/, '') || '/'

const router = createRouter({
  routeTree,
  basepath,
  defaultNotFoundComponent: NotFoundPage,
})

// Mount app - RouterProvider must be outermost so TanStack Router context is available
const container = document.getElementById('root')
if (container) {
  const root = createRoot(container)
  root.render(
    <DevToolsProvider>
      <RouterProvider router={router} />
    </DevToolsProvider>
  )
}
